fun f x -> 
    try 42
    catch 3 ->#first
    
    try 
        42
    catch 3 ->
        #first
    
     
    try
        throw (1,2,"ERROR")
    catch
        | err @ (1, y, 3) -> #first
        | (1,2, "ERROR@") -> #second
        | err @ (1, 2, x) -> #third
    finally ->
        (#fourth, err, x)

fun x () ->
    24

//    try 42
//    catch 3 ->#first
//    
//    try 42
//    catch 3 ->#first
//    finally -> 12
//    
//    try
//        throw (1,2,"ERROR")
//    catch
//        | err @ (1, y, 3) -> #first
//        | (1,2, "ERROR@") -> #second
//        | err @ (1, 2, x) -> #third
//    finally ->
//        (#fourth, err, x)

