def fail(error) ->
    throw error;

def assert_equal(val1, val2) ->
    if val1 != val2
        fail([val1, "!=", val2]);
;

def assert_is(val1, val2) ->
    if val1 isnot val2
        fail([val1, "isnot", val2]);
;


def assert_true(val1) ->
    assert_is(val1, true);

def assert_false(val1) ->
    assert_is(val1, false);


def assert_throw_any(fn) ->
    try
        fn()
        fail(["exception expected", fn])
    catch e
        true;
;

